### PR TITLE
52 adding to cart bug

### LINKED ISSUE #52: adding to cart after checkout bug fix
I’m getting an error in cart homes controller when trying to add a home to a cart on localhost:

"
undefined method `<<' for {}:Hash Did you mean? <
@contents << { home: home_id, checkin: checkin_date, checkout: checkout_date, total_days: total_days }
from line 12
"

I see where the error would happen though in the initialize we do @contents = session_contents || [ ] but session contents comes in as a hash so shoveling wouldnt work there

i got the same error when I check out then try to add another item to my cart

i see where the error is its just a matter of figuring out how to rewrite the cart model to always use a hash

### PR DESCRIPTION
**Pull request by jwashke**
I think its fixed, does someone want to pull down and double check when they have a chance.
closes #52

### CODE REVIEW

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -2,27 +2,35 @@ module ApplicationHelper
...
+      "alert-danger"    # Red
+    when "alert"
+      "alert-warning"   # Yellow
+    when "notice"
+      "alert-info"      # Blue
+    else
+      flash_type.to_s
+    end
+  end
+
```
Comment (theonlyrao) [inline app/helpers/application_helper.rb]: this is nice refactoring

File: db/migrate/20160514212340_change_suspended_on_homes_to_enum.rb [hunk 2]
```diff
@@ -0,0 +1,6 @@
+class ChangeSuspendedOnHomesToEnum < ActiveRecord::Migration
+  def change
+    remove_column :homes, :suspended
+    add_column :homes, :status, :integer, default: 0
+  end
```
Comment (theonlyrao) [inline db/migrate/20160514212340_change_suspended_on_homes_to_enum.rb]: I'm fine with this change but it would be interesting to know why you thought it was necessary

Comment (jwashke) [inline db/migrate/20160514212340_change_suspended_on_homes_to_enum.rb]: Yeah I should have commented on the diff about the change. I did that because we had the methods

**Comment by theonlyrao** [comment]
That's a ton of great work Josh. I wrote a new test to mimic that error path that you and Patrick noticed and it passed immediately. As well as all the other tests. 

I would have merged this myself but wasn't sure what was going on with the two PRs being open and my old WIP still up there too.  From the commit history it looks like they each just been building off of each other. 

If that's true then I think you can merge this one yourself since I've reviewed it and think it is ok. If I'm not understanding the 2 PRs and WIP relationships correctly then please let us know what's going on with them.

**Comment by jwashke** [comment]
Yeah they are pretty much just building on each other. I'm about to put up another PR too of a bunch of added Model Tests, have a couple more to write before i submit the PR then go pass out for the night.

**Comment by patrickwhardy** [comment]
Nice work. Ran the RSpec, and went through everything in the browser. Looks great! Merging now.
