### PR TITLE
91 add controller tests

### LINKED ISSUE #90: fix test for navbar search

### LINKED ISSUE #117: user deletes a home
I think we need a test in which a user deletes his own home, but I could be wrong - I was just looking at the simple cov output

### LINKED ISSUE #118: user tries to delete another user's account
controller test involving delete to a different user

### LINKED ISSUE #119: avatar not showing up
I tried to upload a photo to my account but it didn't show up

### PR DESCRIPTION
**Pull request by jwashke**
Added Controller tests

Fix user_params not allowing avatar

closes #90 
closes #117 
closes #119 
closes #118

### CODE REVIEW

File: spec/controllers/users_controller_spec.rb [hunk 1]
```diff
@@ -0,0 +1,270 @@
...
+        admin = create(:admin)
+        user = create(:user)
+        ApplicationController.any_instance.stubs(:current_user).returns(admin)
+        delete :destroy, slug: user.slug
+        expect(session[:user_id]).to eq(nil)
+      end
+    end
+
+    context "as a user trying to delete another user" do
+      it "sets the user based on the path" do
```
Comment (theonlyrao) [inline spec/controllers/users_controller_spec.rb]: awesome here's the test we were definitely missing according to simplecov

**Comment by theonlyrao** [comment]
really thorough Josh, this is great
